config/routes.rb
Tugas4image::Application.routes.draw do
	root :to => "images#index" 
	resources :images

end

app/models/image.rb
class Image < ActiveRecord::Base
mount_uploader :image, ImageUploader
	
  	validates :img_name, presence: true
  	validates :image, presence: true
  	validate :file_size

  	def file_size
		errors[:image] << "You cannot upload a file greater than 200kb" if image.size > 0.2.megabytes
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
  	@images = Image.all
  end

  def new
  	@image = Image.new
  end

  def create
  	@image = Image.new(img_params)
  	if @image.save
  		flash[:notice] = "Image successfully uploaded!"
  		redirect_to action: "index"
  	else
  		flash[:error] = "data not valid"
        render "new"
  	end
  end

  def edit
  	@image = Image.find_by_id(params[:id])
  end

  def update
  	@image = Image.find_by_id(params[:id])
  	if @image.update(img_params)
  		flash[:notice] = "Image successfully updated!"
          redirect_to action: 'index'
  	else
  		flash[:error] = "data not valid"
  		render 'edit'
  	end
  end

  def show
  	@image = Image.find_by_id(params[:id])
  end

  def destroy
  	@image = Image.find_by_id(params[:id])
  	if @image.destroy
        flash[:notice] = "Image successfully deleted"
        redirect_to action: 'index'
    else
        flash[:error] = "fails delete a records"
        redirect_to action: 'index'
    end
  end

  private
  	def img_params
      params.require(:image).permit(:img_name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image, :html => {:class => "form-horizontal", :role => "form", :multipart => true} do |f| %>
	<div class="form-group">
		<%= f.label :img_name, "Title:", class: "col-sm-2 control-label" %>
		<div class="col-sm-5">
			<%= f.text_field :img_name, {:class => "form-control", :required => "required", :placeholder => "Image title .."} %>
		</div>
		<% if @image.errors[:img_name].any? %>
		<div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
			<div class="alert alert-danger" style="padding:1%; padding-left:3%; margin:0;">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<strong>Error!</strong> title <%= @image.errors[:img_name].first unless @image.errors[:img_name].blank? %>
			</div>
		</div>
		<% end %>
	</div>
	<div class="form-group">
		<%= f.label :image, "Select Image :", class: "col-sm-2 control-label" %>
		<div class="col-sm-5">
			<div class="fileinput fileinput-new" data-provides="fileinput">
			  <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"><%= image_tag @image.image if @image.image? %></div>
			  <div>
			    <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span>
			    <%= f.file_field :image %></span>
			    <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
			  </div>
			</div>
		</div>
		<% if @image.errors[:image].any? %>
		<div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
			<div class="alert alert-danger" style="padding:1%; padding-left:3%; margin:0;">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<strong>Error!</strong> image <%= @image.errors[:image].first unless @image.errors[:image].blank? %>
			</div>
		</div>
		<% end %>
	</div>
	<div class="form-group">
		<div class="col-sm-10 col-sm-offset-2">
			<%= f.submit "Submit", class: "btn btn-default btn-primary" %> 
		</div>
	</div>
<% end %>

app/views/images/edit.html.erb
<% content_for :index do -%>
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
<% end -%>
<% content_for :script do -%>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
<% end -%>
<div class="container">
	<div class="page-header">
	  <h1>Edit image</h1>
	</div>
	<%= render 'form' %>
</div>

app/views/images/index.html.erb
<div class="container">
	<div class="page-header">
	  <h1>Tugas Training CRUD Image  <%= link_to "Upload Image", {:controller => "images", :action => "new" }, :class => "btn btn-sm btn-primary" %></h1>
	  
	</div>
		<% if flash[:notice] %>
			<div class="alert alert-success" style="margin-top:2%">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<strong>Success!</strong> <%= flash[:notice] %>
			</div>
		<% end %>


			<% @images.each do | img | %>

<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
	<div class = "panel" style="width:150px" align = "center">
			<div class = "list-group-item" style="width:150px" align = "center">
			<a href="<%= image_path(img.id) %>">
		  	<figure>
		  		<%= image_tag img.image.url(:thumb) if img.image? %>
			</a>
				<figcaption>Title:<%= img.img_name %><figcaption>
			</figure>
			<%= link_to 'Edit', edit_image_path(img.id), :class => "btn btn-xs btn-success" %>
				<%= link_to 'Delete', image_path(img.id), method: "DELETE", data: {confirm: 'Delete image ? '}, :class => "btn btn-xs btn-danger" %>	
			
			</div>	
	</div>
</div>
			<% end %>
	

app/views/images/new.html.erb
<% content_for :index do -%>
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
<% end -%>
<% content_for :script do -%>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
<% end -%>
<div class="container">
	<div class="page-header">
	  <h1>Upload image</h1>
	</div>
	<%= render 'form' %>
</div>

app/views/images/show.html.erb
<% content_for :index do -%>
	<style>
		.img-center {margin:0 auto 2% auto;}
	</style>
<% end %>
<div class="container">
	<div class="page-header">
	  <h1><%= @image.img_name %></h1>
	</div>
	<div class="row">
		<%= image_tag @image.image.url(:display), :class => "img-center"%>
	</div>
	<div class="row">
		<%= link_to "Back", {:controller => "images", :action => "index" }, :class => "btn btn-success" %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tugas4image</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= yield(:index) %>
</head>
<body>
<%= yield %>


<script src="//code.jquery.com/jquery.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="https://raw.githubusercontent.com/LeaVerou/prefixfree/gh-pages/prefixfree.min.js"></script>
<%= yield(:script) %>
</body>
</html>